auth_enabled: false

limits_config:
  retention_period: 30d # Change as needed
  allow_structured_metadata: true
  volume_enabled: true

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: loki
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki # Change as needed

schema_config:
  configs:
  - from: 2020-05-15 # Change as needed
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index # Change as needed
    cache_location: /tmp/loki/index_cache # Change as needed
  filesystem:
    directory: /tmp/loki/chunks # Change as needed

pattern_ingester:
  enabled: true