receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'odoo'
          scrape_interval: 5s # <-- Delay between scrape jobs
          static_configs:
            - targets: ['odoo:8069']  # Change as needed
          metrics_path: '/metrics'    # <-- Path for prometheus to scrap from

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]
    metrics:
      receivers: [otlp, prometheus]
      exporters: [prometheus]
